title: Tech@MisterSpex
email: your-email@example.com
description: Tech@MisterSpex
baseurl: "http://misterspex.tech" # the subpath of your site, e.g. /blog
url: "http://misterspex.tech" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: msxtech
github_username:  misterspex

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

gems: ['jekyll-twitter-plugin']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
